language: node_js
node_js:
    - lts/*
cache:
    directories:
        - node_modules
branches:
    only:
        - master

install:
    - npm install
script:
    - npm run lint
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master
